apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: my-little-app  #Your app's name
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: my-little-app
      spec:
        containers:
        - name: my-little-app  #Your app will be the running container you built
          image: gcr.io/nodejs-205715/my-little-app:v1
          imagePullPolicy: Always
  ---
  kind: Service
  apiVersion: v1
  metadata:
    name: my-little-app-load-balancer   #This will be the name of your load balancer
  spec:
    selector:
      app: my-little-app  #The load balancer will be attached to the app you specify by name here
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
    type: LoadBalancer
    loadBalancerSourceRanges:  #Firewall rules
    - 151.140.0.0/16
    - 165.130.0.0/16
    - 207.11.0.0/17
    - 50.207.27.182/32
    - 98.6.11.8/29